/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as BlogsRenderingRouteImport } from './routes/blogs/rendering'
import { Route as ApiAuthorRouteImport } from './routes/api/author'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRenderingRoute = BlogsRenderingRouteImport.update({
  id: '/blogs/rendering',
  path: '/blogs/rendering',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthorRoute = ApiAuthorRouteImport.update({
  id: '/api/author',
  path: '/api/author',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/author': typeof ApiAuthorRoute
  '/blogs/rendering': typeof BlogsRenderingRoute
  '/blogs/': typeof BlogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/author': typeof ApiAuthorRoute
  '/blogs/rendering': typeof BlogsRenderingRoute
  '/blogs': typeof BlogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/author': typeof ApiAuthorRoute
  '/blogs/rendering': typeof BlogsRenderingRoute
  '/blogs/': typeof BlogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/author' | '/blogs/rendering' | '/blogs/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/author' | '/blogs/rendering' | '/blogs'
  id: '__root__' | '/' | '/api/author' | '/blogs/rendering' | '/blogs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAuthorRoute: typeof ApiAuthorRoute
  BlogsRenderingRoute: typeof BlogsRenderingRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/rendering': {
      id: '/blogs/rendering'
      path: '/blogs/rendering'
      fullPath: '/blogs/rendering'
      preLoaderRoute: typeof BlogsRenderingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/author': {
      id: '/api/author'
      path: '/api/author'
      fullPath: '/api/author'
      preLoaderRoute: typeof ApiAuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAuthorRoute: ApiAuthorRoute,
  BlogsRenderingRoute: BlogsRenderingRoute,
  BlogsIndexRoute: BlogsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
